name: Build & Release

on:
  push:
    tags:
      - "v*" # example v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
          profile: minimal

      - name: List installed Rust targets
        run: rustup target list --installed

      - name: Build Rust plugin
        run: |
          cargo clean
          cargo build --release --target wasm32-unknown-unknown
          mkdir -p wasm
          cp target/wasm32-unknown-unknown/release/swc_plugin_remove_data_testid.wasm wasm/

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
